# Generated by Django 2.2.1 on 2019-05-21 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestfulAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='Budget',
            new_name='budget',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='Goal',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='Name',
            new_name='name',
        ),
    ]
